# Generated by Django 4.2.3 on 2023-07-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ABSSharedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=300)),
                ("description", models.CharField(max_length=1000)),
                ("synchronized", models.BooleanField(default=False)),
                ("created", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GlobalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=300)),
                ("owner", models.CharField(max_length=1000)),
                ("description", models.CharField(max_length=1000)),
                ("endpoint", models.CharField(max_length=1000)),
                (
                    "sync_status",
                    models.IntegerField(
                        choices=[
                            (4, "Known"),
                            (1, "Pending"),
                            (2, "Accepted"),
                            (3, "Denied"),
                        ],
                        default=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Timers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("seconds", models.IntegerField(default=10)),
                (
                    "timer_type",
                    models.IntegerField(
                        choices=[
                            (1, "Global"),
                            (2, "External request"),
                            (3, "Petitions"),
                        ],
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester", models.CharField(max_length=1000)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Pending"), (2, "Accepted"), (3, "Denied")],
                        default=1,
                    ),
                ),
                ("synchronized", models.BooleanField(default=False)),
                (
                    "related_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.absshareddata",
                    ),
                ),
            ],
        ),
    ]
