# Generated by Django 4.2.3 on 2024-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20230717_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absshareddata",
            name="identifier",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="globaldata",
            name="identifier",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
