# Generated by Django 4.2.3 on 2023-09-05 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20230717_1053"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("dosage", models.CharField(max_length=50)),
                ("frequency", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="absshareddata",
            name="identifier",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="globaldata",
            name="identifier",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_visit", models.DateField()),
                ("diagnosis", models.CharField(max_length=300)),
                ("allergies", models.CharField(max_length=200)),
                (
                    "medication",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.medication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expedient",
            fields=[
                (
                    "absshareddata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.absshareddata",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=50)),
                ("social_security_number", models.CharField(max_length=9)),
                ("address", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                (
                    "medical_history",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.medicalhistory",
                    ),
                ),
            ],
            bases=("core.absshareddata",),
        ),
    ]
