# Generated by Django 4.2.3 on 2023-09-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_medication_alter_absshareddata_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expedient",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="expedient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expedient",
            name="gender",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="expedient",
            name="name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="expedient",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="expedient",
            name="social_security_number",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="allergies",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="diagnosis",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="last_visit",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medication",
            name="dosage",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="medication",
            name="frequency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="medication",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
