# Generated by Django 4.2.3 on 2024-01-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_absshareddata_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globaldata",
            name="last_sync_status",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
