# Generated by Django 4.2.3 on 2024-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_url", models.CharField(max_length=1000)),
                ("account_path", models.CharField(max_length=1000)),
                ("keystore_password", models.CharField(blank=True, max_length=1000)),
                ("smc_address", models.CharField(max_length=1000)),
            ],
        ),
    ]
